### ISSUE TITLE
Is this deployed somewhere?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-bloc-tutorial#4]
@LuchoTurtle is this deployed somewhere I can test it e.g. GitHub Pages? :shipit: 

# Todo

+ [ ] Follow the example we already have in https://github.com/dwyl/app for deploying a `Flutter` App to `GitHub Pages`. 🙏

**Comment by LuchoTurtle** [comment]
It's not. Was waiting for #3 to get merged and then got caught on other issues.

**Comment by nelsonic** [comment]
Cool. Let's time-box deployment using `GitHub Pages` as it's a method we already use and know how to do. 🙏

**Comment by LuchoTurtle** [comment]
Going to be working on this next 🆗

**Comment by nelsonic** [comment]
Thanks. Keep us posted.
